// Code generated by solo-kit. DO NOT EDIT.

package v1

import (
	gloo_solo_io "github.com/solo-io/gloo/projects/gloo/pkg/api/v1"

	"github.com/solo-io/solo-kit/pkg/utils/hashutils"
	"go.uber.org/zap"
)

type ApiSnapshot struct {
	Secrets   gloo_solo_io.SecretsByNamespace
	Upstreams gloo_solo_io.UpstreamsByNamespace
	Ingresses IngressesByNamespace
}

func (s ApiSnapshot) Clone() ApiSnapshot {
	return ApiSnapshot{
		Secrets:   s.Secrets.Clone(),
		Upstreams: s.Upstreams.Clone(),
		Ingresses: s.Ingresses.Clone(),
	}
}

func (s ApiSnapshot) Hash() uint64 {
	return hashutils.HashAll(
		s.hashSecrets(),
		s.hashUpstreams(),
		s.hashIngresses(),
	)
}

func (s ApiSnapshot) hashSecrets() uint64 {
	return hashutils.HashAll(s.Secrets.List().AsInterfaces()...)
}

func (s ApiSnapshot) hashUpstreams() uint64 {
	return hashutils.HashAll(s.Upstreams.List().AsInterfaces()...)
}

func (s ApiSnapshot) hashIngresses() uint64 {
	return hashutils.HashAll(s.Ingresses.List().AsInterfaces()...)
}

func (s ApiSnapshot) HashFields() []zap.Field {
	var fields []zap.Field
	fields = append(fields, zap.Uint64("secrets", s.hashSecrets()))
	fields = append(fields, zap.Uint64("upstreams", s.hashUpstreams()))
	fields = append(fields, zap.Uint64("ingresses", s.hashIngresses()))

	return append(fields, zap.Uint64("snapshotHash", s.Hash()))
}
