// Code generated by solo-kit. DO NOT EDIT.

package v1

import (
	"testing"

	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
	_ "k8s.io/client-go/plugin/pkg/client/auth/gcp"
)

func TestIngresssoloio(t *testing.T) {
	RegisterFailHandler(Fail)
	RunSpecs(t, "Ingresssoloio Suite")
}
