// Code generated by solo-kit. DO NOT EDIT.

package v1

import (
	"fmt"

	"github.com/solo-io/go-utils/hashutils"
	"go.uber.org/zap"
)

type StatusSnapshot struct {
	Services   KubeServiceList
	Insgresses IngressList
}

func (s StatusSnapshot) Clone() StatusSnapshot {
	return StatusSnapshot{
		Services:   s.Services.Clone(),
		Insgresses: s.Insgresses.Clone(),
	}
}

func (s StatusSnapshot) Hash() uint64 {
	return hashutils.HashAll(
		s.hashServices(),
		s.hashInsgresses(),
	)
}

func (s StatusSnapshot) hashServices() uint64 {
	return hashutils.HashAll(s.Services.AsInterfaces()...)
}

func (s StatusSnapshot) hashInsgresses() uint64 {
	return hashutils.HashAll(s.Insgresses.AsInterfaces()...)
}

func (s StatusSnapshot) HashFields() []zap.Field {
	var fields []zap.Field
	fields = append(fields, zap.Uint64("services", s.hashServices()))
	fields = append(fields, zap.Uint64("insgresses", s.hashInsgresses()))

	return append(fields, zap.Uint64("snapshotHash", s.Hash()))
}

type StatusSnapshotStringer struct {
	Version    uint64
	Services   []string
	Insgresses []string
}

func (ss StatusSnapshotStringer) String() string {
	s := fmt.Sprintf("StatusSnapshot %v\n", ss.Version)

	s += fmt.Sprintf("  Services %v\n", len(ss.Services))
	for _, name := range ss.Services {
		s += fmt.Sprintf("    %v\n", name)
	}

	s += fmt.Sprintf("  Insgresses %v\n", len(ss.Insgresses))
	for _, name := range ss.Insgresses {
		s += fmt.Sprintf("    %v\n", name)
	}

	return s
}

func (s StatusSnapshot) Stringer() StatusSnapshotStringer {
	return StatusSnapshotStringer{
		Version:    s.Hash(),
		Services:   s.Services.NamespacesDotNames(),
		Insgresses: s.Insgresses.NamespacesDotNames(),
	}
}
