// Code generated by solo-kit. DO NOT EDIT.

package v1

import (
	"github.com/solo-io/solo-kit/pkg/utils/hashutils"
	"go.uber.org/zap"
)

type StatusSnapshot struct {
	Ingresses IngressesByNamespace
	Services  ServicesByNamespace
}

func (s StatusSnapshot) Clone() StatusSnapshot {
	return StatusSnapshot{
		Ingresses: s.Ingresses.Clone(),
		Services:  s.Services.Clone(),
	}
}

func (s StatusSnapshot) Hash() uint64 {
	return hashutils.HashAll(
		s.hashIngresses(),
		s.hashServices(),
	)
}

func (s StatusSnapshot) hashIngresses() uint64 {
	return hashutils.HashAll(s.Ingresses.List().AsInterfaces()...)
}

func (s StatusSnapshot) hashServices() uint64 {
	return hashutils.HashAll(s.Services.List().AsInterfaces()...)
}

func (s StatusSnapshot) HashFields() []zap.Field {
	var fields []zap.Field
	fields = append(fields, zap.Uint64("ingresses", s.hashIngresses()))
	fields = append(fields, zap.Uint64("services", s.hashServices()))

	return append(fields, zap.Uint64("snapshotHash", s.Hash()))
}
