// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/solo-io/gloo/projects/gateway/api/v2/gateway.proto

package v2

import (
	bytes "bytes"
	fmt "fmt"
	math "math"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	v1 "github.com/solo-io/gloo/projects/gloo/pkg/api/v1"
	core "github.com/solo-io/solo-kit/pkg/api/v1/resources/core"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

//
//A Gateway describes a single Listener (bind address:port)
//and the routing configuration to upstreams that are reachable via a specific port on the Gateway Proxy itself.
type Gateway struct {
	// if set to false, only use virtual services without ssl configured.
	// if set to true, only use virtual services with ssl configured.
	Ssl bool `protobuf:"varint,1,opt,name=ssl,proto3" json:"ssl,omitempty"`
	// the bind address the gateway should serve traffic on
	BindAddress string `protobuf:"bytes,3,opt,name=bind_address,json=bindAddress,proto3" json:"bind_address,omitempty"`
	// bind ports must not conflict across gateways for a single proxy
	BindPort uint32 `protobuf:"varint,4,opt,name=bind_port,json=bindPort,proto3" json:"bind_port,omitempty"`
	// top level plugin configuration for all routes on the gateway
	Plugins *v1.ListenerPlugins `protobuf:"bytes,5,opt,name=plugins,proto3" json:"plugins,omitempty"`
	// Status indicates the validation status of this resource.
	// Status is read-only by clients, and set by gloo during validation
	Status core.Status `protobuf:"bytes,6,opt,name=status,proto3" json:"status" testdiff:"ignore"`
	// Metadata contains the object metadata for this resource
	Metadata core.Metadata `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata"`
	// Enable ProxyProtocol support for this listener
	UseProxyProto *types.BoolValue `protobuf:"bytes,8,opt,name=use_proxy_proto,json=useProxyProto,proto3" json:"use_proxy_proto,omitempty"`
	// The type of gateway being created
	// HttpGateway creates a listener with an http_connection_manager
	// TcpGateway creates a listener with a tcp proxy filter
	//
	// Types that are valid to be assigned to GatewayType:
	//	*Gateway_HttpGateway
	//	*Gateway_TcpGateway
	GatewayType isGateway_GatewayType `protobuf_oneof:"GatewayType"`
	// deprecated: use proxyNames
	GatewayProxyName string `protobuf:"bytes,11,opt,name=gateway_proxy_name,json=gatewayProxyName,proto3" json:"gateway_proxy_name,omitempty"`
	// By default, each Gateway is exposed on the default `gateway-proxy-v2` which lives in the Gloo installation namespace.
	// Use `proxyNames` to expose Gateways on custom proxies deployed by the user via the [Gloo Helm Chart](https://gloo.solo.io/installation/gateway/kubernetes/#list-of-gloo-helm-chart-values)
	//
	// > Note: when using camel-case proxy names in the Helm chart, they should be converted to kebab-case for use with `proxyNames`, such that:
	// `gatewayProxyV2` in the Helm Values becomes `gateway-proxy-v2` in the list of proxyNames
	ProxyNames           string   `protobuf:"bytes,12,opt,name=proxy_names,json=proxyNames,proto3" json:"proxy_names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Gateway) Reset()         { *m = Gateway{} }
func (m *Gateway) String() string { return proto.CompactTextString(m) }
func (*Gateway) ProtoMessage()    {}
func (*Gateway) Descriptor() ([]byte, []int) {
	return fileDescriptor_07ebb625f16d49f4, []int{0}
}
func (m *Gateway) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Gateway.Unmarshal(m, b)
}
func (m *Gateway) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Gateway.Marshal(b, m, deterministic)
}
func (m *Gateway) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gateway.Merge(m, src)
}
func (m *Gateway) XXX_Size() int {
	return xxx_messageInfo_Gateway.Size(m)
}
func (m *Gateway) XXX_DiscardUnknown() {
	xxx_messageInfo_Gateway.DiscardUnknown(m)
}

var xxx_messageInfo_Gateway proto.InternalMessageInfo

type isGateway_GatewayType interface {
	isGateway_GatewayType()
	Equal(interface{}) bool
}

type Gateway_HttpGateway struct {
	HttpGateway *HttpGateway `protobuf:"bytes,9,opt,name=http_gateway,json=httpGateway,proto3,oneof"`
}
type Gateway_TcpGateway struct {
	TcpGateway *TcpGateway `protobuf:"bytes,10,opt,name=tcp_gateway,json=tcpGateway,proto3,oneof"`
}

func (*Gateway_HttpGateway) isGateway_GatewayType() {}
func (*Gateway_TcpGateway) isGateway_GatewayType()  {}

func (m *Gateway) GetGatewayType() isGateway_GatewayType {
	if m != nil {
		return m.GatewayType
	}
	return nil
}

func (m *Gateway) GetSsl() bool {
	if m != nil {
		return m.Ssl
	}
	return false
}

func (m *Gateway) GetBindAddress() string {
	if m != nil {
		return m.BindAddress
	}
	return ""
}

func (m *Gateway) GetBindPort() uint32 {
	if m != nil {
		return m.BindPort
	}
	return 0
}

func (m *Gateway) GetPlugins() *v1.ListenerPlugins {
	if m != nil {
		return m.Plugins
	}
	return nil
}

func (m *Gateway) GetStatus() core.Status {
	if m != nil {
		return m.Status
	}
	return core.Status{}
}

func (m *Gateway) GetMetadata() core.Metadata {
	if m != nil {
		return m.Metadata
	}
	return core.Metadata{}
}

func (m *Gateway) GetUseProxyProto() *types.BoolValue {
	if m != nil {
		return m.UseProxyProto
	}
	return nil
}

func (m *Gateway) GetHttpGateway() *HttpGateway {
	if x, ok := m.GetGatewayType().(*Gateway_HttpGateway); ok {
		return x.HttpGateway
	}
	return nil
}

func (m *Gateway) GetTcpGateway() *TcpGateway {
	if x, ok := m.GetGatewayType().(*Gateway_TcpGateway); ok {
		return x.TcpGateway
	}
	return nil
}

func (m *Gateway) GetGatewayProxyName() string {
	if m != nil {
		return m.GatewayProxyName
	}
	return ""
}

func (m *Gateway) GetProxyNames() string {
	if m != nil {
		return m.ProxyNames
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Gateway) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Gateway_HttpGateway)(nil),
		(*Gateway_TcpGateway)(nil),
	}
}

type HttpGateway struct {
	// names of the the virtual services, which contain the actual routes for the gateway
	// if the list is empty, all virtual services will apply to this gateway (with accordance to tls flag above).
	VirtualServices []core.ResourceRef `protobuf:"bytes,1,rep,name=virtual_services,json=virtualServices,proto3" json:"virtual_services"`
	// only one of `virtualServices` or `virtualServiceSelector` should be provided
	// rather than providing
	VirtualServiceSelector map[string]string `protobuf:"bytes,2,rep,name=virtual_service_selector,json=virtualServiceSelector,proto3" json:"virtual_service_selector,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// http gateway configuration
	Plugins              *v1.HttpListenerPlugins `protobuf:"bytes,8,opt,name=plugins,proto3" json:"plugins,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *HttpGateway) Reset()         { *m = HttpGateway{} }
func (m *HttpGateway) String() string { return proto.CompactTextString(m) }
func (*HttpGateway) ProtoMessage()    {}
func (*HttpGateway) Descriptor() ([]byte, []int) {
	return fileDescriptor_07ebb625f16d49f4, []int{1}
}
func (m *HttpGateway) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpGateway.Unmarshal(m, b)
}
func (m *HttpGateway) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpGateway.Marshal(b, m, deterministic)
}
func (m *HttpGateway) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpGateway.Merge(m, src)
}
func (m *HttpGateway) XXX_Size() int {
	return xxx_messageInfo_HttpGateway.Size(m)
}
func (m *HttpGateway) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpGateway.DiscardUnknown(m)
}

var xxx_messageInfo_HttpGateway proto.InternalMessageInfo

func (m *HttpGateway) GetVirtualServices() []core.ResourceRef {
	if m != nil {
		return m.VirtualServices
	}
	return nil
}

func (m *HttpGateway) GetVirtualServiceSelector() map[string]string {
	if m != nil {
		return m.VirtualServiceSelector
	}
	return nil
}

func (m *HttpGateway) GetPlugins() *v1.HttpListenerPlugins {
	if m != nil {
		return m.Plugins
	}
	return nil
}

type TcpGateway struct {
	// Name of the destinations the gateway can route to
	Destinations []*v1.TcpHost `protobuf:"bytes,1,rep,name=destinations,proto3" json:"destinations,omitempty"`
	// tcp gateway configuration
	Plugins              *v1.TcpListenerPlugins `protobuf:"bytes,8,opt,name=plugins,proto3" json:"plugins,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *TcpGateway) Reset()         { *m = TcpGateway{} }
func (m *TcpGateway) String() string { return proto.CompactTextString(m) }
func (*TcpGateway) ProtoMessage()    {}
func (*TcpGateway) Descriptor() ([]byte, []int) {
	return fileDescriptor_07ebb625f16d49f4, []int{2}
}
func (m *TcpGateway) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TcpGateway.Unmarshal(m, b)
}
func (m *TcpGateway) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TcpGateway.Marshal(b, m, deterministic)
}
func (m *TcpGateway) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TcpGateway.Merge(m, src)
}
func (m *TcpGateway) XXX_Size() int {
	return xxx_messageInfo_TcpGateway.Size(m)
}
func (m *TcpGateway) XXX_DiscardUnknown() {
	xxx_messageInfo_TcpGateway.DiscardUnknown(m)
}

var xxx_messageInfo_TcpGateway proto.InternalMessageInfo

func (m *TcpGateway) GetDestinations() []*v1.TcpHost {
	if m != nil {
		return m.Destinations
	}
	return nil
}

func (m *TcpGateway) GetPlugins() *v1.TcpListenerPlugins {
	if m != nil {
		return m.Plugins
	}
	return nil
}

func init() {
	proto.RegisterType((*Gateway)(nil), "gateway.solo.io.v2.Gateway")
	proto.RegisterType((*HttpGateway)(nil), "gateway.solo.io.v2.HttpGateway")
	proto.RegisterMapType((map[string]string)(nil), "gateway.solo.io.v2.HttpGateway.VirtualServiceSelectorEntry")
	proto.RegisterType((*TcpGateway)(nil), "gateway.solo.io.v2.TcpGateway")
}

func init() {
	proto.RegisterFile("github.com/solo-io/gloo/projects/gateway/api/v2/gateway.proto", fileDescriptor_07ebb625f16d49f4)
}

var fileDescriptor_07ebb625f16d49f4 = []byte{
	// 713 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xcd, 0x4e, 0xdb, 0x4c,
	0x14, 0xc5, 0x21, 0x40, 0x32, 0x0e, 0x82, 0x6f, 0xc4, 0x87, 0x4c, 0x50, 0x49, 0xc8, 0x2a, 0x0b,
	0x6a, 0x8b, 0xb0, 0x28, 0x04, 0x75, 0x41, 0xd4, 0x0a, 0x5a, 0xb5, 0x55, 0x64, 0x10, 0x8b, 0x6e,
	0xa2, 0x89, 0x73, 0x63, 0xa6, 0x38, 0x1e, 0x6b, 0x66, 0x1c, 0x9a, 0x2d, 0x7d, 0x99, 0x3e, 0x4a,
	0x1f, 0xa1, 0xea, 0x82, 0x45, 0xdf, 0x80, 0x3e, 0x41, 0xe5, 0xf1, 0x38, 0x21, 0xfc, 0x14, 0x58,
	0x79, 0xee, 0xdc, 0x7b, 0xce, 0xfd, 0x3b, 0x23, 0xa3, 0xd7, 0x3e, 0x95, 0x67, 0x71, 0xd7, 0xf6,
	0xd8, 0xc0, 0x11, 0x2c, 0x60, 0x2f, 0x29, 0x73, 0xfc, 0x80, 0x31, 0x27, 0xe2, 0xec, 0x0b, 0x78,
	0x52, 0x38, 0x3e, 0x91, 0x70, 0x41, 0x46, 0x0e, 0x89, 0xa8, 0x33, 0x6c, 0x64, 0xa6, 0x1d, 0x71,
	0x26, 0x19, 0xc6, 0x99, 0x99, 0x60, 0x6d, 0xca, 0xec, 0x61, 0xa3, 0xbc, 0xe2, 0x33, 0x9f, 0x29,
	0xb7, 0x93, 0x9c, 0xd2, 0xc8, 0xf2, 0x86, 0xcf, 0x98, 0x1f, 0x80, 0xa3, 0xac, 0x6e, 0xdc, 0x77,
	0x2e, 0x38, 0x89, 0x22, 0xe0, 0x42, 0xfb, 0xb7, 0xef, 0x29, 0x44, 0x7d, 0xcf, 0xa9, 0x4c, 0x73,
	0x6f, 0x3b, 0x03, 0x90, 0xa4, 0x47, 0x24, 0xd1, 0x10, 0xe7, 0x09, 0x10, 0x21, 0x89, 0x8c, 0xb3,
	0x1c, 0x5b, 0x4f, 0x00, 0x70, 0xe8, 0x3f, 0xa3, 0xa2, 0xcc, 0xd6, 0x90, 0xdd, 0xc7, 0xa7, 0x99,
	0x58, 0x1a, 0x1c, 0x71, 0xf6, 0x55, 0x0f, 0xb2, 0xdc, 0x7c, 0x1e, 0x32, 0x88, 0x7d, 0x1a, 0xea,
	0xb6, 0x6a, 0xbf, 0xf2, 0x68, 0xe1, 0x30, 0xdd, 0x03, 0x5e, 0x46, 0xb3, 0x42, 0x04, 0x96, 0x51,
	0x35, 0xea, 0x05, 0x37, 0x39, 0xe2, 0x4d, 0x54, 0xea, 0xd2, 0xb0, 0xd7, 0x21, 0xbd, 0x1e, 0x07,
	0x21, 0xac, 0xd9, 0xaa, 0x51, 0x2f, 0xba, 0x66, 0x72, 0x77, 0x90, 0x5e, 0xe1, 0x75, 0x54, 0x54,
	0x21, 0x11, 0xe3, 0xd2, 0xca, 0x57, 0x8d, 0xfa, 0xa2, 0x5b, 0x48, 0x2e, 0xda, 0x8c, 0x4b, 0xfc,
	0x0a, 0x2d, 0xe8, 0x74, 0xd6, 0x5c, 0xd5, 0xa8, 0x9b, 0x8d, 0x17, 0x76, 0x52, 0xca, 0x78, 0xe3,
	0x1f, 0xa8, 0x90, 0x10, 0x02, 0x6f, 0xa7, 0x41, 0x6e, 0x16, 0x8d, 0x0f, 0xd1, 0x7c, 0x3a, 0x7d,
	0x6b, 0x5e, 0xe1, 0x56, 0x6c, 0x8f, 0x71, 0x18, 0xe3, 0x8e, 0x95, 0xaf, 0xb5, 0xf6, 0xe3, 0xaa,
	0x32, 0xf3, 0xe7, 0xaa, 0xf2, 0x9f, 0x04, 0x21, 0x7b, 0xb4, 0xdf, 0x6f, 0xd6, 0xa8, 0x1f, 0x32,
	0x0e, 0x35, 0x57, 0xc3, 0xf1, 0x2e, 0x2a, 0x64, 0x9b, 0xb7, 0x16, 0x14, 0xd5, 0xea, 0x34, 0xd5,
	0x47, 0xed, 0x6d, 0xe5, 0x13, 0x32, 0x77, 0x1c, 0x8d, 0x5b, 0x68, 0x29, 0x16, 0xd0, 0x51, 0x83,
	0xee, 0xa8, 0x61, 0x59, 0x05, 0x45, 0x50, 0xb6, 0x53, 0x39, 0xda, 0x99, 0x1c, 0xed, 0x16, 0x63,
	0xc1, 0x29, 0x09, 0x62, 0x70, 0x17, 0x63, 0x01, 0xed, 0x04, 0xd1, 0x56, 0x12, 0x7f, 0x83, 0x4a,
	0x67, 0x52, 0x46, 0x1d, 0xad, 0x74, 0xab, 0xa8, 0x08, 0x2a, 0xf6, 0x5d, 0xe5, 0xdb, 0x47, 0x52,
	0x46, 0x7a, 0x11, 0x47, 0x33, 0xae, 0x79, 0x36, 0x31, 0xf1, 0x01, 0x32, 0xa5, 0x37, 0x21, 0x41,
	0x8a, 0x64, 0xe3, 0x3e, 0x92, 0x13, 0xef, 0x06, 0x07, 0x92, 0x63, 0x0b, 0x6f, 0xa1, 0xec, 0xb5,
	0xe9, 0x86, 0x42, 0x32, 0x00, 0xcb, 0x54, 0xeb, 0x5c, 0xd6, 0x1e, 0x55, 0xf7, 0x27, 0x32, 0x00,
	0x5c, 0x41, 0xe6, 0x24, 0x4a, 0x58, 0x25, 0x15, 0x86, 0xa2, 0xcc, 0x2f, 0x9a, 0xab, 0x97, 0xd7,
	0xf9, 0x3c, 0xca, 0xf9, 0x17, 0x97, 0xd7, 0x79, 0x84, 0x0b, 0x9a, 0x40, 0xb4, 0x16, 0x91, 0xa9,
	0x33, 0x9e, 0x8c, 0x22, 0xa8, 0xfd, 0xcc, 0x21, 0xf3, 0x46, 0x5f, 0xf8, 0x3d, 0x5a, 0x1e, 0x52,
	0x2e, 0x63, 0x12, 0x74, 0x04, 0xf0, 0x21, 0xf5, 0x40, 0x58, 0x46, 0x75, 0xb6, 0x6e, 0x36, 0xd6,
	0xa6, 0x97, 0xe2, 0x82, 0x60, 0x31, 0xf7, 0xc0, 0x85, 0xbe, 0xde, 0xcb, 0x92, 0x06, 0x1e, 0x6b,
	0x1c, 0x8e, 0x91, 0x75, 0x8b, 0xab, 0x23, 0x20, 0x00, 0x4f, 0x32, 0x6e, 0xe5, 0x14, 0xe7, 0xfe,
	0x23, 0x63, 0xb6, 0x4f, 0xa7, 0x28, 0x8f, 0x35, 0xfa, 0x6d, 0x28, 0xf9, 0xc8, 0x5d, 0x1d, 0xde,
	0xeb, 0xc4, 0xfb, 0x13, 0x45, 0xa7, 0x6a, 0xd8, 0x9c, 0x56, 0x74, 0xc2, 0xff, 0x90, 0xaa, 0xcb,
	0xef, 0xd0, 0xfa, 0x3f, 0x72, 0x26, 0xef, 0xef, 0x1c, 0x46, 0xea, 0xfd, 0x15, 0xdd, 0xe4, 0x88,
	0x57, 0xd0, 0xdc, 0x30, 0xd1, 0x95, 0x95, 0x53, 0x77, 0xa9, 0xd1, 0xcc, 0xed, 0x1a, 0xb5, 0x6f,
	0x06, 0x42, 0x93, 0x6d, 0xe3, 0x3d, 0x54, 0xea, 0x81, 0x90, 0x34, 0x24, 0x92, 0xb2, 0x30, 0x9b,
	0xea, 0xff, 0xd3, 0xb5, 0x9d, 0x78, 0xd1, 0x11, 0x13, 0xd2, 0x9d, 0x0a, 0xc5, 0xcd, 0xdb, 0x1d,
	0x55, 0xef, 0xa0, 0x1e, 0x6a, 0xa8, 0xb5, 0xf7, 0xfd, 0xf7, 0x86, 0xf1, 0x79, 0xe7, 0xc9, 0xff,
	0x81, 0xe8, 0xdc, 0xd7, 0xff, 0x82, 0xee, 0xbc, 0x7a, 0x3d, 0x3b, 0x7f, 0x03, 0x00, 0x00, 0xff,
	0xff, 0xff, 0x47, 0x1b, 0x27, 0x45, 0x06, 0x00, 0x00,
}

func (this *Gateway) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Gateway)
	if !ok {
		that2, ok := that.(Gateway)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Ssl != that1.Ssl {
		return false
	}
	if this.BindAddress != that1.BindAddress {
		return false
	}
	if this.BindPort != that1.BindPort {
		return false
	}
	if !this.Plugins.Equal(that1.Plugins) {
		return false
	}
	if !this.Status.Equal(&that1.Status) {
		return false
	}
	if !this.Metadata.Equal(&that1.Metadata) {
		return false
	}
	if !this.UseProxyProto.Equal(that1.UseProxyProto) {
		return false
	}
	if that1.GatewayType == nil {
		if this.GatewayType != nil {
			return false
		}
	} else if this.GatewayType == nil {
		return false
	} else if !this.GatewayType.Equal(that1.GatewayType) {
		return false
	}
	if this.GatewayProxyName != that1.GatewayProxyName {
		return false
	}
	if this.ProxyNames != that1.ProxyNames {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *Gateway_HttpGateway) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Gateway_HttpGateway)
	if !ok {
		that2, ok := that.(Gateway_HttpGateway)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.HttpGateway.Equal(that1.HttpGateway) {
		return false
	}
	return true
}
func (this *Gateway_TcpGateway) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Gateway_TcpGateway)
	if !ok {
		that2, ok := that.(Gateway_TcpGateway)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.TcpGateway.Equal(that1.TcpGateway) {
		return false
	}
	return true
}
func (this *HttpGateway) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*HttpGateway)
	if !ok {
		that2, ok := that.(HttpGateway)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.VirtualServices) != len(that1.VirtualServices) {
		return false
	}
	for i := range this.VirtualServices {
		if !this.VirtualServices[i].Equal(&that1.VirtualServices[i]) {
			return false
		}
	}
	if len(this.VirtualServiceSelector) != len(that1.VirtualServiceSelector) {
		return false
	}
	for i := range this.VirtualServiceSelector {
		if this.VirtualServiceSelector[i] != that1.VirtualServiceSelector[i] {
			return false
		}
	}
	if !this.Plugins.Equal(that1.Plugins) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *TcpGateway) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*TcpGateway)
	if !ok {
		that2, ok := that.(TcpGateway)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Destinations) != len(that1.Destinations) {
		return false
	}
	for i := range this.Destinations {
		if !this.Destinations[i].Equal(that1.Destinations[i]) {
			return false
		}
	}
	if !this.Plugins.Equal(that1.Plugins) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
