// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/solo-io/gloo/projects/gloo/api/v1/plugins/tcp/tcp.proto

package tcp

import (
	bytes "bytes"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	math "math"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// Contains various settings for Envoy's tcp proxy filter.
// See here for more information: https://www.envoyproxy.io/docs/envoy/v1.10.0/api-v2/config/filter/network/tcp_proxy/v2/tcp_proxy.proto#envoy-api-msg-config-filter-network-tcp-proxy-v2-tcpproxy
type TcpProxySettings struct {
	MaxConnectAttempts   uint32         `protobuf:"varint,1,opt,name=max_connect_attempts,json=maxConnectAttempts,proto3" json:"max_connect_attempts,omitempty"`
	IdleTimeout          *time.Duration `protobuf:"bytes,2,opt,name=idle_timeout,json=idleTimeout,proto3,stdduration" json:"idle_timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TcpProxySettings) Reset()         { *m = TcpProxySettings{} }
func (m *TcpProxySettings) String() string { return proto.CompactTextString(m) }
func (*TcpProxySettings) ProtoMessage()    {}
func (*TcpProxySettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f155c5f0173a62f, []int{0}
}
func (m *TcpProxySettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TcpProxySettings.Unmarshal(m, b)
}
func (m *TcpProxySettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TcpProxySettings.Marshal(b, m, deterministic)
}
func (m *TcpProxySettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TcpProxySettings.Merge(m, src)
}
func (m *TcpProxySettings) XXX_Size() int {
	return xxx_messageInfo_TcpProxySettings.Size(m)
}
func (m *TcpProxySettings) XXX_DiscardUnknown() {
	xxx_messageInfo_TcpProxySettings.DiscardUnknown(m)
}

var xxx_messageInfo_TcpProxySettings proto.InternalMessageInfo

func (m *TcpProxySettings) GetMaxConnectAttempts() uint32 {
	if m != nil {
		return m.MaxConnectAttempts
	}
	return 0
}

func (m *TcpProxySettings) GetIdleTimeout() *time.Duration {
	if m != nil {
		return m.IdleTimeout
	}
	return nil
}

func init() {
	proto.RegisterType((*TcpProxySettings)(nil), "tcp.plugins.gloo.solo.io.TcpProxySettings")
}

func init() {
	proto.RegisterFile("github.com/solo-io/gloo/projects/gloo/api/v1/plugins/tcp/tcp.proto", fileDescriptor_6f155c5f0173a62f)
}

var fileDescriptor_6f155c5f0173a62f = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0x3d, 0x4e, 0x03, 0x31,
	0x10, 0x85, 0x65, 0x84, 0x28, 0x36, 0x20, 0xa1, 0x55, 0x8a, 0x90, 0x22, 0x44, 0x54, 0x69, 0xb0,
	0xf9, 0x69, 0x69, 0x58, 0x38, 0x00, 0x0a, 0xa9, 0x68, 0x56, 0x5e, 0xc7, 0x18, 0xc3, 0xae, 0x67,
	0x64, 0x8f, 0x61, 0xb9, 0x01, 0x47, 0xe0, 0x08, 0xdc, 0x0a, 0x89, 0x93, 0x20, 0xaf, 0x43, 0x07,
	0x12, 0x85, 0xa5, 0x19, 0x7d, 0x6f, 0xfc, 0x49, 0xaf, 0xa8, 0x8c, 0xa5, 0x87, 0xd8, 0x70, 0x05,
	0x9d, 0x08, 0xd0, 0xc2, 0xb1, 0x05, 0x61, 0x5a, 0x00, 0x81, 0x1e, 0x1e, 0xb5, 0xa2, 0x90, 0x37,
	0x89, 0x56, 0x3c, 0x9f, 0x0a, 0x6c, 0xa3, 0xb1, 0x2e, 0x08, 0x52, 0x98, 0x1e, 0x47, 0x0f, 0x04,
	0xe5, 0x64, 0x18, 0x33, 0xe2, 0x29, 0xce, 0xd3, 0x4f, 0xdc, 0xc2, 0x74, 0x6c, 0xc0, 0xc0, 0x10,
	0x12, 0x69, 0xca, 0xf9, 0xe9, 0xcc, 0x00, 0x98, 0x56, 0x8b, 0x61, 0x6b, 0xe2, 0xbd, 0x78, 0xf1,
	0x12, 0x51, 0xfb, 0xf0, 0x17, 0x5f, 0x47, 0x2f, 0xc9, 0x82, 0xcb, 0xfc, 0xe8, 0x8d, 0x15, 0xfb,
	0x2b, 0x85, 0x37, 0x1e, 0xfa, 0xd7, 0x5b, 0x4d, 0x64, 0x9d, 0x09, 0xe5, 0x49, 0x31, 0xee, 0x64,
	0x5f, 0x2b, 0x70, 0x4e, 0x2b, 0xaa, 0x25, 0x91, 0xee, 0x90, 0xc2, 0x84, 0xcd, 0xd9, 0x62, 0x6f,
	0x59, 0x76, 0xb2, 0xbf, 0xca, 0xe8, 0x72, 0x43, 0xca, 0xaa, 0xd8, 0xb5, 0xeb, 0x56, 0xd7, 0x64,
	0x3b, 0x0d, 0x91, 0x26, 0x5b, 0x73, 0xb6, 0x18, 0x9d, 0x1d, 0xf0, 0x6c, 0xe7, 0x3f, 0x76, 0x7e,
	0xbd, 0xb1, 0x57, 0xdb, 0xef, 0x9f, 0x87, 0x6c, 0x39, 0x4a, 0x47, 0xab, 0x7c, 0x53, 0x55, 0x1f,
	0x5f, 0x33, 0x76, 0x77, 0xf1, 0xbf, 0x12, 0xf1, 0xc9, 0xfc, 0x52, 0x64, 0xb3, 0x33, 0x98, 0xce,
	0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x35, 0x3a, 0xbd, 0xf6, 0x8b, 0x01, 0x00, 0x00,
}

func (this *TcpProxySettings) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*TcpProxySettings)
	if !ok {
		that2, ok := that.(TcpProxySettings)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.MaxConnectAttempts != that1.MaxConnectAttempts {
		return false
	}
	if this.IdleTimeout != nil && that1.IdleTimeout != nil {
		if *this.IdleTimeout != *that1.IdleTimeout {
			return false
		}
	} else if this.IdleTimeout != nil {
		return false
	} else if that1.IdleTimeout != nil {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
